### PR TITLE
Add all rules and tests from DepHell

### PR DESCRIPTION
**Pull request by orsinium**

### CODE REVIEW

**Comment by orsinium** [comment]
@dbanty, @LaFa777, review, please

**Comment by orsinium** [comment]
I've uploaded current version on PyPI, so you can try built package.

**Comment by orsinium** [comment]
Ok, let's move on

**Comment by dbanty** [comment]
Sorry I never finished reviewing, I’m away at a conference so I’ve been taking peaks here and there. Looks great from what I’ve read!

**Comment by orsinium** [comment]
Don't hurry, you can have a look at any time, we can do any changes in the next release :)

**Pull request merged**
